### ISSUE TITLE
python

### ISSUE THREAD

**Issue by boldofyoutoassume** [Mizogg/Mizogg-Tools#15]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 972, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by boldofyoutoassume** [comment]
still a bit of a noob when it comes to corrections bro, wouldve fixed it myself but i still have much to learn

**Comment by Mizogg** [comment]
guarda have now block Python API. I have Change the API to Atomic Wallet should be Working on newer version
